### PR TITLE
New Proxmox provider

### PR DESCRIPTION
**Pull request by darknao**
Initial support for Proxmox hypervisor.

This is a work in progress.

For now, only the basic workflow is implemented (download images, create/start/stop basic vms).
Ignition support is not there (yet) so no Openshift deployment is possible.
CloudInit is partially supported.

### CODE REVIEW

**Comment by karmab** [comment]
This is brillant!!!
Do you believe I actually deployed a proxmox vm yesterday yo give it a try?

A couple of comments:

- I tried using rest api without using a specific helper library (nor even requests). Would you be ok if (in the long run) we switched to this approach (to limit dependencies and ease packaging)?
- can auth be based on username/password in proxmoxer ?

Let me know when you want this merged, it doesnt have to be perfect so that we can iterate on top

**Comment by darknao** [comment]
> * I tried using rest api without using a specific helper library (nor even requests). Would you be ok if (in the long run) we switched to this approach (to limit dependencies and ease packaging)?

I'm ok with that. The proxmoxer lib is quite simple and seems very light, I'm not sure I would have done better than that.

>* can auth be based on username/password in proxmoxer ?

Sure it can :)

> Let me know when you want this merged, it doesnt have to be perfect so that we can iterate on top

I'll try to at least get some documentation done and do some more testing in the next couple of days.

**Comment by darknao** [comment]
Ok, I think this is in a  "Good Enough" state and ready for review :)
I've added Ignition support and managed to create a single node cluster with it (with bootstrap).

I have a couple of questions:
in [kvirt/cluster/openshift/__init__.py](https://github.com/karmab/kcli/blob/e062e1e239a38d430ede2e026bb72eae60daa377/kvirt/cluster/openshift/__init__.py#L614C1-L618C3)
```python
    if data['ctlplanes'] == 1 and data['workers'] == 0\
       and 'ctlplane_memory' not in overrides and 'memory' not in overrides:
        data['ctlplane_memory'] = 32768
        warning("Forcing memory of single ctlplane vm to 32G")
    retries = data.get('retries')
```
I'm not sure, but I believe this setting needs to go in `overrides` instead of `data` as it's the one used by `config.plan`.
My last single node was created with the default 16G even though I got the `Forcing memory of single ctlplane vm to 32G` message. But maybe I missed something in my implementation...

The other question / request is about domain and default network:
The Openshift cluster creation default to `karmalabs.corp` and network to `default` even if I set something different in my main config.yml. The only way to change that is to use arguments or parameter files.
I think those two settings should use the main config values if it exists, then fallback to the current default if not. Just like `pool`.
My main issue is there is no `default` network in Proxmox, and you can't really figure out programmatically which one is the right one. So I think it makes sense to have it configured in the default/client config.
What do you think?

**Comment by karmab** [comment]
you re right about the forcing memory thing, addressed in https://github.com/karmab/kcli/commit/0e817b6e84ade0e64952f736fe5c235eb9c6ae67

**Pull request merged**
