### PR TITLE
Feature/support install k3s version

### PR DESCRIPTION
**Pull request by larssb**
Ready for the PR. More comments in the commits. I've tested this on local.

### CODE REVIEW

**Comment by karmab** [comment]
this looks good, ready to merge but can we instead use the following variables
k3s_channel and k3s_version (or even channel and version), k3s seems redondant.

**Comment by larssb** [comment]
The reason for me using the long variable names with the redundant K3S in the name is because of:

```
the parameters now also directly map to
the RancherLabs K3S https://rancher.com/docs/k3s/latest/en/installation/install-options/#options-for-installation-with-script
script install options
```

> The thinking being that it then is transparent that these variables are directly from the K3S install options.

What do you say?

**Comment by karmab** [comment]
your call then!

**Comment by larssb** [comment]
Thank you ....

**Pull request merged**
