### PR TITLE
Added version command to show installed and latest versions

### PR DESCRIPTION
**Pull request by soukron**
This change replaces --version parameter with a command which not only shows the installed version but also checks the latest version available in PyPI.

It has a timeout to not taking so much time in case of network problems and a pass in case of any kind of exception raised by request module.

Another way may be using pip module which could be better as it handles the url internally instead of having hardcoded. That could be an improvement. Feel free to do it better :)

### CODE REVIEW

**Comment by karmab** [comment]
i m still evaluating whether i prefer this pip dependency although i agree it s nice to quickly look if a more recent version is available

**Comment by soukron** [comment]
Would you be more comfortable by running os.system() call and parsing the json with a regexp? It's feasible but ugiler and kcli is about being elegant. Isn't it?

**Comment by soukron** [comment]
Here's a version which uses default already included urillib2 and json libraries. No PIP dependencies.

**Comment by karmab** [comment]
sadly, i believe version should only display the installed version and not a one available

**Pull request closed without merging**
