### PR TITLE
Replace distutils.version with packaging.version for python 3.12

### PR DESCRIPTION
**Pull request by lhp-nemlig**
distutils is used in a single file, but the package has been removed in python 3.12.
https://docs.python.org/3.10/whatsnew/3.10.html#distutils-deprecated

As a result, running kcli under python 3.12 is not possible.

This PR replaces distutils.version.LooseVersion with packaging.version.parse which should be equivalent:
https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html
https://github.com/Azure/azure-cli/pull/17667/files

I believe I have added the pip package requirements in the necessary places, but please verify that.

### CODE REVIEW

**Comment by larssb** [comment]
Nice @lhp-nemlig! Your first `KCLI` PR. @karmab Mr. Lukas is part of the Kubernemlig team in Nemlig 👍 :-D.

**Comment by karmab** [comment]
I m sorry, I'm driving you crazy with this one, but I dont want to add an extra dependency, since this only comes in this github_version filter, let me figure an alternative way to gather exotic versions and so we get rid of LooseVersion

**Comment by lhp-nemlig** [comment]
How about just changing the github api call to always retrieve latest, seems like the github_version function is never used in tag mode?

`data = json.loads(urlopen(f"https://api.github.com/repos/{repo}/{obj}", timeout=5).read())`
vs
`data = json.loads(urlopen(f"https://api.github.com/repos/{repo}/{obj}/latest", timeout=5).read())`

**Comment by karmab** [comment]
> How about just changing the github api call to always retrieve latest, seems like the github_version function is never used in tag mode?
> 
> `data = json.loads(urlopen(f"https://api.github.com/repos/{repo}/{obj}", timeout=5).read())` vs `data = json.loads(urlopen(f"https://api.github.com/repos/{repo}/releases/latest", timeout=5).read())`

sadly that's not valid because latest doesnt always point to latest software, but latest released by the team, that could be a bug fix for an older version

**Comment by karmab** [comment]
so Instead I decided to remove  use of LooseVersion in https://github.com/karmab/kcli/commit/81e7659c51461cca2765aa9e71f1361a848f4cc3
This might have side effects for some specific projects but I ll adjust the filter when finding specific repos not providing the correct latest tag

**Pull request closed without merging**
