### PR TITLE
Allow customizing cluster network with multiple CIDRs

### PR DESCRIPTION
**Pull request by palonsoro**
It would be nice to be able to customize cluster networks and service network at install time.

### CODE REVIEW

**Comment by palonsoro** [comment]
I forgot about this thing for a while. During this time, variables to customize service network and cluster network were added to kcli. However, the one about customizing cluster network allows a single clusternetwork, not multiple CIDRs, so changing the scope of this PR to bring that feature.

I just hope to not leave this undone for much longer :-)

**Comment by palonsoro** [comment]
I'd prefer to have https://github.com/karmab/kcli/issues/384 with a definitive fix and rebase on it.

**Comment by palonsoro** [comment]
**Finally!!!!**

I could finally make some time to review this. It works as expected in IPv4, IPv6 and dualstack.

The idea is:
- Service network is still intended to be customized via `service_network_ipv4` and `service_network_ipv6` only, because only one per kind is possible
- Single pod network CIDR with default hostsubnet length can still be specified via `cluster_network_ipv4` and `cluster_network_ipv6` variables.
- If a "richer" configuration is desired (more than one cluster network for a single IP family, different hostsubnet length...), the whole `cluster_network` variable may be specified. User is responsible of following the correct format and of providing at least one cluster network per IP family.

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/afef690e316ffc1554e77b0491cd38c5da5368c8

**Pull request closed without merging**
